### ISSUE TITLE
Create a index.html for RESTful api online testing

### ISSUE THREAD

**Issue by chromevoid** [NYU-Foxtrot/inventory#39]
**As a** Developer
**I need** database with Bluemix
**So that** our service can work with persistence

**Assumptions:** 
* Website is working with Redis and Bluemix

**Acceptance Criteria:**
```
Given the URL of our application
When visiting the website
Then things are successfully running
```

**Reference:**

**Comment by Chong-Li-nyu** [comment]
Move this issue to next sprint

**Comment by chromevoid** [comment]
Issue aborted
