### ISSUE TITLE
Move models.py and server.py to a folder app

### ISSUE THREAD

**Issue by chromevoid** [NYU-Foxtrot/inventory#43]
**As a** Developer
**I need** a clear folder structure
**So that** files are clean and easy to navigate

**Assumptions:** 
* Move models.py and server.py to a folder app

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Reference:**

**Comment by monabest** [comment]
Probably we could adding "Refactor server.py with restplus" ? I was thinking if we need to refactor the codes according to the new example with restplus?

**Comment by chromevoid** [comment]
No, we will do the restplus during sprint 3. No need to change the code
right now. Make sure that BDD works first.

**Comment by chromevoid** [comment]
You may add a new issue about restplus and move it to icebox.
